RandomForest:
  params:
    n_estimators: 150

AdaBoost:
  params:
    n_estimators: 150

GradientBoost:
  params:
    n_estimators: 150
    learning_rate: 1e-3

Bagging:
  params:
    n_estimators: 150
    max_features: 0.5
    max_samples: 1.0

DecisionTree:
  params:
    
ExtraTree:
  params:
    n_estimators: 150